Added Collections/Wishlist functionality
echaulk2/cdk-test-repo pull request #15
Opened 2022-01-29 00:37 UTC by echaulk2

2022-02-03 12:13 UTC, leavertj requested changes

2022-02-03 12:13 UTC, leavertj commented on functions/collection.ts
> +            ConditionExpression: 'attribute_not_exists(collectionType) AND attribute_not_exists(userID) AND attribute_not_exists(sortKey)'
Also looks like there is some cross-over here with Dynamo operations. I'd try to keep the persistence logic to one class if possible.

2022-02-03 12:13 UTC, leavertj commented on functions/collectionManager.ts
> +      ConditionExpression: 'attribute_exists(sortKey) and attribute_exists(userID)'
Not sure you need this condition

2022-02-03 12:13 UTC, leavertj commented on functions/collectionManager.ts
> +    collection.addGame(game);
what happens if a user tries to add two games in quick succession? Quick enough that two instances of 'addGameToCollection' were executing at the same time attempting to add two different games.

2022-02-03 12:13 UTC, leavertj commented on functions/collection.ts
> +    collectionType: string;
How would you use this attribute to extend the functionality of a wishlist? What if you want to add a few functions specifically for wishlists?

2022-02-12 23:36 UTC, closed without merging

2022-02-12 23:37 UTC, echaulk2 commented
Implementing the changes in this PR in another PR